# Generated by Django 2.1 on 2018-10-27 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donorprofile',
            name='donoraddress',
        ),
    ]
