# Generated by Django 2.1 on 2018-11-03 13:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAddress',
            fields=[
                ('useraddressid', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.CharField(choices=[('Andhra Pradesh', 'Andhra Pradesh'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Assam', 'Assam'), ('Bihar', 'Bihar'), ('Goa', 'Goa'), ('Haryana', 'Haryana'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Jammu and Kashmir', 'Jammu and Kashmir'), ('Jharkhand', 'Jharkhand'), ('karnataka', 'karnataka'), ('Kerala', 'Kerala'), ('Madhya Pradesh', 'Madhya Pradesh'), ('Maharashtra', 'Maharashtra'), ('Manipur', 'Manipur'), ('Meghalaya', 'Meghalaya'), ('Mizoram', 'Mizoram'), ('Nagaland', 'Nagaland'), ('Odisha', 'Odisha'), ('Punjab', 'Punjab'), ('Rajasthan', 'Rajasthan'), ('Sikkim', 'Sikkim'), ('Tamil Nadu', 'Tamil Nadu'), ('Goa', 'Goa'), ('Telangana', 'Telangana'), ('Tripura', 'Tripura'), ('Uttar Pradesh', 'Uttar Pradesh'), ('Uttarakhand', 'Uttarakhand'), ('West Bengal', 'West Bengal')], max_length=30)),
                ('city', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=100)),
                ('birth', models.CharField(max_length=200)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('transgender', 'Transgender')], max_length=15)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('blood', models.CharField(choices=[('A+', 'A-'), ('A-', 'A+'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserHistory',
            fields=[
                ('userhistoryid', models.AutoField(primary_key=True, serialize=False)),
                ('donation_date', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('userprofileid', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=200, null=True)),
                ('feedback', models.CharField(max_length=1000, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='acceptoraddress',
            name='user',
        ),
        migrations.RemoveField(
            model_name='acceptorhistory',
            name='user',
        ),
        migrations.RemoveField(
            model_name='acceptorprofile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='donoraddress',
            name='user',
        ),
        migrations.RemoveField(
            model_name='donorhistory',
            name='user',
        ),
        migrations.RemoveField(
            model_name='donorprofile',
            name='user',
        ),
        migrations.AddField(
            model_name='bloodcamp',
            name='duration',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='pathlab',
            field=models.CharField(choices=[('Chennai', 'Chennai'), ('Bangalore', 'Bangalore'), ('Patna', 'Patna'), ('Mumbai', 'Mumbai'), ('Hyderabad', 'Hyderabad'), ('Kolkata', 'Kolkata'), ('Delhi', 'Delhi'), ('Jamshedpur', 'Jamshedpur')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bloodcampdonor',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.DeleteModel(
            name='AcceptorAddress',
        ),
        migrations.DeleteModel(
            name='AcceptorHistory',
        ),
        migrations.DeleteModel(
            name='AcceptorProfile',
        ),
        migrations.DeleteModel(
            name='DonorAddress',
        ),
        migrations.DeleteModel(
            name='DonorHistory',
        ),
        migrations.DeleteModel(
            name='DonorProfile',
        ),
    ]
