# Generated by Django 2.1 on 2018-11-03 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20181103_1907'),
    ]

    operations = [
        migrations.CreateModel(
            name='BloodAvailability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('threshhold', models.IntegerField(default=0)),
                ('bloodgroup_A_plus', models.IntegerField(default=0)),
                ('bloodgroup_A_minus', models.IntegerField(default=0)),
                ('bloodgroup_B_plus', models.IntegerField(default=0)),
                ('bloodgroup_B_minus', models.IntegerField(default=0)),
                ('bloodgroup_O_plus', models.IntegerField(default=0)),
                ('bloodgroup_O_minus', models.IntegerField(default=0)),
                ('bloodgroup_AB_plus', models.IntegerField(default=0)),
                ('bloodgroup_AB_minus', models.IntegerField(default=0)),
            ],
        ),
    ]
